/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientChatWindow.java
 *
 * Created on Jan 28, 2011, 11:31:46 AM
 */

package com.chat.frame;

import java.util.Vector;

/**
 *
 * @author Sudipta Bera
 */
public class ClientChatWindow extends javax.swing.JFrame {

    private String loginuser=null;
    /** Creates new form ClientChatWindow */
    public ClientChatWindow() {


    }

    public ClientChatWindow(String userid)
    {
        loginuser=userid;
        initComponents();
        txtAreaChat.setText(loginuser+" is now in room");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaChat = new javax.swing.JTextArea();
        pnlTabbed = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tpnlUser = new javax.swing.JTabbedPane();
        tpanelRoom = new javax.swing.JTabbedPane();
        pnlBottom = new javax.swing.JPanel();
        pnlFont = new javax.swing.JPanel();
        lblBold = new javax.swing.JLabel();
        lblBold1 = new javax.swing.JLabel();
        pnlTextInput = new javax.swing.JPanel();
        txtInputText = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAction = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuOption = new javax.swing.JMenu();
        mnuRoom = new javax.swing.JMenu();
        mnuMobile = new javax.swing.JMenu();
        mnuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAreaChat.setColumns(20);
        txtAreaChat.setRows(5);
        jScrollPane1.setViewportView(txtAreaChat);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        pnlTabbed.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabbedPane1.addTab("User", tpnlUser);
        jTabbedPane1.addTab("Room", tpanelRoom);

        javax.swing.GroupLayout pnlTabbedLayout = new javax.swing.GroupLayout(pnlTabbed);
        pnlTabbed.setLayout(pnlTabbedLayout);
        pnlTabbedLayout.setHorizontalGroup(
            pnlTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        pnlTabbedLayout.setVerticalGroup(
            pnlTabbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pnlBottom.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlFont.setBackground(new java.awt.Color(204, 204, 255));

        lblBold.setFont(new java.awt.Font("Arial", 0, 24));
        lblBold.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBold.setText("B");
        lblBold.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblBold1.setFont(new java.awt.Font("Verdana", 2, 24));
        lblBold1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBold1.setText("I");
        lblBold1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlFontLayout = new javax.swing.GroupLayout(pnlFont);
        pnlFont.setLayout(pnlFontLayout);
        pnlFontLayout.setHorizontalGroup(
            pnlFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFontLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBold, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBold1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(683, Short.MAX_VALUE))
        );
        pnlFontLayout.setVerticalGroup(
            pnlFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblBold)
                .addComponent(lblBold1))
        );

        pnlTextInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSend.setFont(new java.awt.Font("Courier New", 1, 18));
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleSendText(evt);
            }
        });

        javax.swing.GroupLayout pnlTextInputLayout = new javax.swing.GroupLayout(pnlTextInput);
        pnlTextInput.setLayout(pnlTextInputLayout);
        pnlTextInputLayout.setHorizontalGroup(
            pnlTextInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTextInputLayout.createSequentialGroup()
                .addComponent(txtInputText, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSend)
                .addContainerGap())
        );
        pnlTextInputLayout.setVerticalGroup(
            pnlTextInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTextInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txtInputText, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFont, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTextInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addComponent(pnlFont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTextInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlTabbed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnlTabbed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBottom, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        mnuAction.setText("Action");

        jMenuItem1.setText("AV");
        mnuAction.add(jMenuItem1);

        jMenuBar1.add(mnuAction);

        mnuOption.setText("Options");
        jMenuBar1.add(mnuOption);

        mnuRoom.setText("Room");
        jMenuBar1.add(mnuRoom);

        mnuMobile.setText("Mobile");
        jMenuBar1.add(mnuMobile);

        mnuHelp.setText("Help");
        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleSendText(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleSendText
        // TODO add your handling code here:

       // String chatText=txtAreaChat.getText();
        txtAreaChat.setText(txtAreaChat.getText()+"\n"+loginuser+": "+txtInputText.getText());
        txtInputText.setText("");
        
    }//GEN-LAST:event_handleSendText

    /**
    * @param args the command line arguments
    */
    /*
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientChatWindow().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBold;
    private javax.swing.JLabel lblBold1;
    private javax.swing.JMenu mnuAction;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuMobile;
    private javax.swing.JMenu mnuOption;
    private javax.swing.JMenu mnuRoom;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlFont;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTabbed;
    private javax.swing.JPanel pnlTextInput;
    private javax.swing.JTabbedPane tpanelRoom;
    private javax.swing.JTabbedPane tpnlUser;
    private javax.swing.JTextArea txtAreaChat;
    private javax.swing.JTextField txtInputText;
    // End of variables declaration//GEN-END:variables

}
